### ISSUE TITLE
Add option to show a banner with an input field

### ISSUE THREAD

**Issue by oferRounds** [alexruperez/UIUserNotificationSettings-Extension#3]
It would be great if such one, similar to the one used by the Messages app, could be added.

**Comment by alexruperez** [comment]
That would be awesome. In fact it was the first thing I looked creating this library. Unfortunately, Apple does not allow this using the public API.

Thanks @oferRounds

**Comment by alexruperez** [comment]
@oferRounds Added UIUserNotificationActionBehaviorTextInput compatibility! :+1: https://github.com/alexruperez/UIUserNotificationSettings-Extension/commit/45c68be14d99722e8598ce7c0c73c89ca2be874b

Update to v0.1.2

**Comment by oferRounds** [comment]
Yay! Amazing! Thanks a lot! 
Looks great :+1:
