### ISSUE TITLE
Add new Local Notification with set date/time

### ISSUE THREAD

**Issue by Shozuke** [alexruperez/UIUserNotificationSettings-Extension#5]
Is it possible to add a Local Notification with a set date/time locally?

I saw your example and you make the notification pop after 1 sec, but I wanted to use it out of appDelegate and create X notifications all with different times and dates.

Thanks

**Comment by alexruperez** [comment]
@Shozuke yes, it's possible, check out: http://stackoverflow.com/a/18540270/958806
