### ISSUE TITLE
notify the notification when application is in open or  active.

### ISSUE THREAD

**Issue by arishanapalli** [alexruperez/UIUserNotificationSettings-Extension#6]
Hi
Alex,
UIUserNotificationSetting is working really good,
It will be more useful for following issue.

Can u please let me know, how to show localNotification when the applicationDidBecomeActive.
its working when app is in background Mode,
I need it when application is opened & closed.
When application is opened the notification is not showing for me.

```
- (void)applicationDidBecomeActive:(UIApplication *)application {
    // Restart any tasks that were paused (or not yet started) while the application was inactive. If the application was previously in the background, optionally refresh the user interface.

    UILocalNotification *localNotification = UILocalNotification.new;
    localNotification.fireDate = [NSDate dateWithTimeIntervalSinceNow:2];
    localNotification.alertBody = @"congratulation !";
    localNotification.alertAction = @"Open 😉";
    localNotification.category = @"default_category";
    [application scheduleLocalNotification:localNotification];

}
```

Your valuable inputs will be appreciated.

**Comment by alexruperez** [comment]
You will receive the local notification in [application:didReceiveLocalNotification:](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIApplicationDelegate_Protocol/#//apple_ref/occ/intfm/UIApplicationDelegate/application:didReceiveLocalNotification:) and you have to show it in your app with your own UI. You could use [hyperoslo/Whisper](https://github.com/hyperoslo/Whisper#shouts).
